#!/usr/bin/env bash
#MISE description="Lint Markdown files in the project"
#USAGE flag "-f --fix" help="Automatically fix supported issues"

set -euo pipefail

ARGS=()

if [ "${usage_fix:-false}" = "true" ]; then
  ARGS+=("--fix")
fi

markdownlint-cli2 "${ARGS[@]}" .
