name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MISE_TASK_RUN_AUTO_INSTALL: "false"

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install lint tools
        uses: jdx/mise-action@f10502fc09dadecfefb962fff68ce77213930204 # v4.2.2
        with:
          install_args: bun npm:prettier

      - name: Run linter
        run: mise lint:prettier --fix

      - name: Verify linters produced no changes
        run: git diff --exit-code

  markdown:
    name: Markdown
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install lint tools
        uses: jdx/mise-action@f10502fc09dadecfefb962fff68ce77213930204 # v4.2.2
        with:
          install_args: bun npm:markdownlint-cli2

      - name: Run linter
        run: mise lint:markdown

  hadolint:
    name: Hadolint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install lint tools
        uses: jdx/mise-action@f10502fc09dadecfefb962fff68ce77213930204 # v4.2.2
        with:
          install_args: aqua:hadolint/hadolint

      - name: Run linter
        run: mise lint:hadolint

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install lint tools
        uses: jdx/mise-action@f10502fc09dadecfefb962fff68ce77213930204 # v4.2.2
        with:
          install_args: aqua:koalaman/shellcheck

      - name: Run linter
        run: mise lint:shellcheck
